import { test, expect } from '@playwright/test';
test('exploration, rich edges, filters, interruption, history and keyboard', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  const canvas = page.locator('#graph');
  await expect(canvas).toHaveAttribute('data-state', 'settled');
  await expect(page.locator('[data-node="document"]')).toHaveClass(/focus/);
  await expect(page.locator('[data-label="reviewer"]')).toBeVisible();
  await page.getByRole('button', { name: 'Inspect author', exact: true }).click();
  await expect(page.locator('#detail-title')).toHaveText('author');
  await expect(page.locator('#detail-type')).toHaveText('Document → Person');
  await page.getByRole('button', { name: 'Focus Person', exact: true }).click();
  await expect(canvas).toHaveAttribute('data-state', 'settled');
  await expect(page.locator('[data-node="person"]')).toHaveClass(/focus/);
  await expect(page.locator('[data-label="mentor"]')).toBeVisible();
  await page.getByRole('button', { name: '← Back' }).click();
  await expect(canvas).toHaveAttribute('data-state', 'settled');
  await expect(page.locator('#focus-name')).toHaveText('Document');
  await page.getByLabel('identity.ts').uncheck();
  await expect(canvas).toHaveAttribute('data-state', 'settled');
  await expect(page.locator('[data-label="mentor"]')).toHaveCount(0);
  await page.getByLabel('Jump to a node').selectOption('team');
  await page.getByLabel('Jump to a node').selectOption('topic');
  await expect(canvas).toHaveAttribute('data-state', 'settled');
  await expect(page.locator('#focus-name')).toHaveText('Topic');
  await page.getByLabel('Follow connections').selectOption('both');
  await expect(canvas).toHaveAttribute('data-state', 'settled');
  const document = page.getByRole('button', { name: 'Focus Document', exact: true });
  await document.focus(); await page.keyboard.press('Enter');
  await expect(canvas).toHaveAttribute('data-state', 'settled');
  await expect(page.locator('#focus-name')).toHaveText('Document');
  await page.getByLabel('Arrangement').selectOption('horizontal');
  await expect(canvas).toHaveAttribute('data-state', 'settled');
  await expect(page.getByRole('alert')).toBeHidden();
  expect(errors).toEqual([]);
  await page.screenshot({ path: 'test-results/demo.png', fullPage: true });
});
